# Generated by Django 5.2.18 on 2026-10-06 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Unpaid'), ('paid', 'Paid')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='salarypayment',
            name='month',
            field=models.DateField(),
        ),
    ]
