# Generated by Django 5.2.18 on 2026-10-06 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendance_payment_date_attendance_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarypayment',
            name='month',
            field=models.DateField(help_text='Salary cycle start date'),
        ),
    ]
